name: Dependabot auto-merge

on:
  workflow_dispatch: # Disabled - upstream artifact, not needed for Pathfinder operations
jobs:
  auto-merge:
    if: github.actor == 'dependabot[bot]' && github.event.pull_request.user.login == 'dependabot[bot]'
    uses: verygoodplugins/.github/.github/workflows/dependabot-auto-merge.yml@main
    secrets: inherit
